version: '3'
services:
  ticket-board:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ticket-board
    container_name: CUI-Tickets
    ports:
      - "5000:5000"
    volumes:
      - .:/app